# Generated by Django 3.2.4 on 2021-09-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
