# Generated by Django 3.2.4 on 2021-10-02 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secondlevelcategory',
            options={'verbose_name': 'Second Level Category', 'verbose_name_plural': 'Second Level Categories'},
        ),
        migrations.AlterModelOptions(
            name='superproductcategory',
            options={'verbose_name': 'First Level Category', 'verbose_name_plural': 'First Level Categories'},
        ),
    ]
