# Generated by Django 3.2.4 on 2021-09-22 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='User',
            new_name='user',
        ),
    ]
