# Generated by Django 3.2.4 on 2021-09-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(help_text='Price should Grater than 20'),
        ),
    ]
