# Generated by Django 3.2.4 on 2021-09-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210915_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='payment_option',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
