# Generated by Django 3.2.4 on 2021-09-24 07:38

from django.db import migrations, models
import django.db.models.deletion
import mainapp.utils


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAlternativeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative_image', models.ImageField(upload_to=mainapp.utils.image_name_change)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.product')),
            ],
        ),
    ]
