# Generated by Django 3.2.4 on 2021-09-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_shippingaddress_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ordered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
