# Generated by Django 3.2.4 on 2021-09-15 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_orderitem_ordered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='order',
            new_name='order_item',
        ),
    ]
