# Generated by Django 3.2.4 on 2021-09-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_remove_shippingaddress_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='secondlevelcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True),
        ),
    ]
