# Generated by Django 3.2.4 on 2021-09-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20210916_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Discount Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=2000, verbose_name='Product Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price should Grater than 20', max_digits=8, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='brand_name',
            field=models.CharField(max_length=200, verbose_name='Brand Name'),
        ),
    ]
