# Generated by Django 3.2.4 on 2021-09-19 08:49

from django.db import migrations, models
import mainapp.utils


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20210919_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=mainapp.utils.image_name_change, verbose_name='Product Image'),
        ),
    ]
