# Generated by Django 3.2.4 on 2021-09-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondlevelcategory',
            name='product_category',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Product Category Name (2nd level)'),
        ),
        migrations.AlterField(
            model_name='superproductcategory',
            name='first_level_category',
            field=models.CharField(blank=True, help_text='Like Electronic or Beauty Products or Sport and OutDoors', max_length=100, null=True),
        ),
    ]
