# Generated by Django 3.2.4 on 2021-09-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20210919_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(help_text='Price should Grater than 20', verbose_name='Price'),
        ),
    ]
