# Generated by Django 3.2.4 on 2021-09-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price should Grater than 20', max_digits=8, verbose_name='Price'),
        ),
    ]
