# Generated by Django 3.2.4 on 2021-09-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superproductcategory',
            name='first_level_category',
            field=models.CharField(blank=True, help_text='Like Electronic or Beauty Products or Sport and OutDoors', max_length=100, null=True, unique=True),
        ),
    ]
