# Generated by Django 3.2.4 on 2021-09-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_alter_superproductcategory_first_level_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='brand_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Brand Name'),
        ),
    ]
