# Generated by Django 3.2.4 on 2021-09-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_alter_productcategory_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Discount Name'),
        ),
    ]
