# Generated by Django 3.2.4 on 2021-09-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_auto_20210919_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
