# Generated by Django 3.2.4 on 2021-09-21 08:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='merchant documents'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_merchant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='pan_no',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='User Pan Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
    ]
